// ============================================
// DADOS DO GLOSSÁRIO
// ============================================

const GLOSSARIO = [
    // ============================================
    // MECÂNICAS DE COMBATE
    // ============================================
    { termo: "Hindrance", categoria: "combate",
      def: "Efeito que impede ou atrapalha o movimento/ação do Pokémon (stun, slow, fear, sono, etc). É o 'controle de grupo' do UNITE." },
    { termo: "CC (Crowd Control)", categoria: "combate",
      def: "Sinônimo de Hindrance. Qualquer efeito que controle o inimigo: atordoamento, lentidão, medo, stun, sono." },
    { termo: "Unstoppable", categoria: "combate",
      def: "Estado em que o Pokémon fica imune a hindrances. Não pode ser atordoado, puxado ou lentificado." },
    { termo: "Invincible", categoria: "combate",
      def: "Estado em que o Pokémon não pode receber dano nem ser alvo de habilidades. Diferente de Unstoppable, que só bloqueia CC." },
    { termo: "Bound", categoria: "combate",
      def: "Efeito que prende o Pokémon no lugar (como a ult do Charizard). Algumas habilidades (ex: Unite Move da Alcremie) são canceladas se a usuária ficar bound." },
    { termo: "Stun", categoria: "combate",
      def: "Atordoamento. O Pokémon atingido não pode se mover nem usar habilidades por um curto período." },
    { termo: "Slow", categoria: "combate",
      def: "Redução da velocidade de movimento. Geralmente dura 1-3s e pode ser aplicado em área." },
    { termo: "Pull", categoria: "combate",
      def: "Efeito que puxa o inimigo em sua direção (ex: Snorlax com Block)." },
    { termo: "Knockback", categoria: "combate",
      def: "Empurra o inimigo para trás. Pode interromper habilidades canalizadas." },
    { termo: "Buff", categoria: "combate",
      def: "Efeito positivo aplicado em si mesmo ou em aliados: escudo, aumento de ataque, velocidade, etc." },
    { termo: "Debuff", categoria: "combate",
      def: "Efeito negativo aplicado em inimigos: redução de ataque, defesa, velocidade, etc." },
    { termo: "Shield", categoria: "combate",
      def: "Escudo. Absorve dano antes do HP. Pode ser concedido a si mesmo ou a aliados." },
    { termo: "Heal / Cura", categoria: "combate",
      def: "Restaura HP. Pode ser instantâneo, em área, ou over-time (HoT)." },
    { termo: "Sustain", categoria: "combate",
      def: "Capacidade de um Pokémon de se manter vivo em lutas prolongadas, seja por cura, escudo ou resistência." },
    { termo: "Burst", categoria: "combate",
      def: "Dano alto concentrado em um curto espaço de tempo. Típico de assassinos." },
    { termo: "DPS", categoria: "combate",
      def: "Damage Per Second (Dano por Segundo). Medida de dano contínuo ao longo do tempo." },
    { termo: "HoT", categoria: "combate",
      def: "Heal over Time (Cura por Tempo). Cura que acontece em ticks ao longo de alguns segundos." },
    { termo: "DoT", categoria: "combate",
      def: "Damage over Time (Dano por Tempo). Dano que acontece em ticks após o golpe inicial." },
    { termo: "CDR", categoria: "combate",
      def: "Cooldown Reduction (Redução de Recarga). Reduz o tempo de espera para usar habilidades novamente." },
    { termo: "Crit Rate", categoria: "combate",
      def: "Chance de um ataque causar dano crítico (dano aumentado)." },
    { termo: "Crit Damage", categoria: "combate",
      def: "Multiplicador de dano quando um crítico acontece." },

    // ============================================
    // CLASSE E PAPEL
    // ============================================
    { termo: "Support / Suporte", categoria: "classe",
      def: "Classe focada em curar, dar escudos e buffar aliados. Essencial em qualquer time." },
    { termo: "Attacker / Atacante", categoria: "classe",
      def: "Classe focada em dano à distância. Frágil, mas com alto DPS." },
    { termo: "Defender / Defensor", categoria: "classe",
      def: "Classe tanque. Muito HP e defesa, capaz de iniciar lutas e absorver dano." },
    { termo: "All-Rounder", categoria: "classe",
      def: "Classe equilibrada. Dano e resistência medianos, boa na maioria dos casos." },
    { termo: "Speedster", categoria: "classe",
      def: "Classe assassina. Alto dano e mobilidade, mas muito frágil. Focada em eliminar os carries inimigos rapidamente e recuar." },
    { termo: "ADC / Carry", categoria: "classe",
      def: "Attack Damage Carry. Pokémon que começa fraco mas fica muito forte no late game." },
    { termo: "Ranged", categoria: "classe",
      def: "Pokémon que ataca à distância. Oposto de Melee." },
    { termo: "Melee", categoria: "classe",
      def: "Pokémon que ataca de perto. Oposto de Ranged." },
    { termo: "Atacante Especial / Sp. Atk", categoria: "classe",
      def: "Pokémon cujo dano escala com Ataque Especial, não com Ataque físico." },
    { termo: "Atacante Físico / Atk", categoria: "classe",
      def: "Pokémon cujo dano escala com Ataque físico, não com Ataque Especial." },

    // ============================================
    // MAPA E OBJETIVOS
    // ============================================
    { termo: "Lane / Rota", categoria: "mapa",
      def: "Uma das três rotas do mapa: Top (superior), Bot (inferior) e Central/Jungle." },
    { termo: "Jungle / Selva", categoria: "mapa",
      def: "Área central do mapa, cheia de Pokémon selvagens. Geralmente ocupada por Speedsters." },
    { termo: "Farm / Farmar", categoria: "mapa",
      def: "Matar Pokémon selvagens para ganhar experiência e subir de nível." },
    { termo: "Last Hit / Smite", categoria: "mapa",
      def: "Dá o golpe final em um Pokémon selvagem. Só os aliados de quem dá o last hit recebe a experiência." },
    { termo: "Aeos Energy / Energia Aeos / Pontos", categoria: "mapa",
      def: "Recurso que você coleta ao matar Pokémon selvagens/inimigos. Usada para marcar pontos." },
    { termo: "Gol / Marcar Ponto", categoria: "mapa",
      def: "Depositar energia Aeos na zona de gol inimiga. Cada gol dá pontos ao time." },
    { termo: "Goal Zone / Zona de Gol / Torre", categoria: "mapa",
      def: "Área onde você marca pontos. Cada time tem 5." },
    { termo: "Score / Pontuação", categoria: "mapa",
      def: "Total de pontos do time. Quem tem mais pontos ao final dos 10 minutos vence." },
    { termo: "T1, T2, T3", categoria: "mapa",
      def: "Nomenclatura, em ordem crescente, da torre mais externa para a mais interna." },

    // ============================================
    // ESTRATÉGIAS
    // ============================================
    { termo: "Poke", categoria: "estrategia",
      def: "Atacar o inimigo à distância, de forma segura, sem comprometer-se em lutas. Desgasta o alvo aos poucos. Vem do inglês, perturbar/incomodar." },
    { termo: "Peel", categoria: "estrategia",
      def: "Proteger um aliado (geralmente o carry) usando CC ou dano para afastar inimigos que o estão atacando." },
    { termo: "Kite", categoria: "estrategia",
      def: "Atacar enquanto se afasta do inimigo. Típico de ranged Pokémon contra melees." },
    { termo: "Zonear", categoria: "estrategia",
      def: "Controlar uma área do mapa, impedindo que inimigos passem ou farmem ali." },
    { termo: "Gank", categoria: "estrategia",
      def: "Rotação do Jungler, se ele rotacionou pra top lane, ele gankou na top." },
    { termo: "Roaming / Rotação", categoria: "estrategia",
      def: "Mover-se entre rotas para ajudar aliados em lutas ou capturar objetivos." },
    { termo: "Team Fight", categoria: "estrategia",
      def: "Luta em equipe, geralmente 5v5, em torno de um objetivo ou defesa de gol." },
    { termo: "Engage / Iniciar", categoria: "estrategia",
      def: "Começar uma luta. Geralmente feito por Defenders ou All-Rounders, pulando no time inimigo." },
    { termo: "Disengage / Desengajar", categoria: "estrategia",
      def: "Sair de uma luta quando está em desvantagem. Suportes/Tanks ajudam nisso com slow e escudo." },
    { termo: "Dive", categoria: "estrategia",
      def: "Avançar agressivamente sobre o time inimigo, geralmente focando o carry adversário." },
    { termo: "Focus / Focar", categoria: "estrategia",
      def: "Todos do time atacarem o mesmo alvo ao mesmo tempo. Geralmente o carry inimigo." },
    { termo: "Trocar pontos", categoria: "estrategia",
      def: "Marcar pontos nas costas do time inimigo, enquanto eles estão pontuam em outra parte do mapa." },
    { termo: "Splitar", categoria: "estrategia",
      def: "Dividir o time em duas frentes para pressionar objetivos diferentes ao mesmo tempo." },
    { termo: "Snipe / Snipar", categoria: "estrategia",
      def: "Usar habilidades de longo alcance para roubar um objetivo (ex: Rayquaza) do time inimigo." },

    // ============================================
    // BUILDS E ITENS
    // ============================================
    { termo: "Build", categoria: "build",
      def: "Conjunto de itens e emblemas equipados por um Pokémon. Define o estilo de jogo dele." },
    { termo: "Held Item", categoria: "build",
      def: "Item equipado permanentemente pelo Pokémon. Dá atributos passivos (ex: Wise Glasses, Buddy Barrier)." },
    { termo: "Battle Item", categoria: "build",
      def: "Item ativável durante a partida (ex: Eject Button, Potion). Só se pode equipar 1 por vez." },
    { termo: "Boost Emblems", categoria: "build",
      def: "Sistema de bônus pequenos. Cada emblema dá +1 atributo e -1 outro. Bônus de cor ativam em tiers." },
    { termo: "Set Bonus", categoria: "build",
      def: "Bônus ativado ao equipar múltiplos emblemas da mesma cor. Ativa em tiers (2/4/6 ou 3/5/7)." },
    { termo: "Tier List", categoria: "build",
      def: "Classificação em tiers (S, A, B, C...). Variável e relativo." },
    { termo: "Meta", categoria: "build",
      def: "Estratégia/composição mais eficaz no momento atual. Muda conforme patches e balanceamento." },
    { termo: "Loadout", categoria: "build",
      def: "Sinônimo de build. Conjunto de itens e emblemas." },
    { termo: "Combo", categoria: "build",
      def: "Sequência de habilidades usadas em ordem para maximizar dano, cura, CC ou aproveitamento de cooldown." },
    { termo: "Cooldown (CD)", categoria: "build",
      def: "Tempo de espera entre usos de uma habilidade." }]